twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    paths:
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator

when@test:
    twig:
        strict_variables: true
        form_themes:
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
